/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.gladwell.http4k

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun test() {
        assertEquals(1, 1)
    }
}
